veterinary/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:sessions => "sessions"}
  resources :service_orders
  resources :detail_orders
  resources :appointments
  resources :products
  resources :pets
  resources :customers

   root :to => 'appointments#index'

end

veterinary/app/models/customer.rb
# == Schema Information
#
# Table name: customers
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  address    :string(255)
#  dni        :string(255)
#  city       :string(255)
#  phone      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Customer < ActiveRecord::Base
end

veterinary/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, :address, :dni, :city, :phone)
    end
end

veterinary/app/helpers/customers_helper.rb
module CustomersHelper
end

veterinary/app/views/customers/_form.html.erb
<%= form_for @customer, :html => { :class => "form-horizontal customer" } do |f| %>

    <% if @customer.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @customer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@customer[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address, :class => 'form-control' %>
    </div>
    <%= error_span(@customer[:address]) %>
  </div>
  <div class="control-group">
    <%= f.label :dni, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :dni, :class => 'form-control' %>
    </div>
    <%= error_span(@customer[:dni]) %>
  </div>
  <div class="control-group">
    <%= f.label :city, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :city, :class => 'form-control' %>
    </div>
    <%= error_span(@customer[:city]) %>
  </div>
  <div class="control-group">
    <%= f.label :phone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :phone, :class => 'form-control' %>
    </div>
    <%= error_span(@customer[:phone]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            customers_path, :class => 'btn btn-default' %>

<% end %>

veterinary/app/views/customers/edit.html.erb
<%- model_class = Customer -%>
<div class="content-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>

<section class="content">
    <%= render :partial => 'form' %>
</section>

veterinary/app/views/customers/index.html.erb
<%- model_class = Customer -%>
<div class="content-header">
  <h1>
    <%=t '.title', :default => model_class.model_name.human.pluralize.titleize %>
    <div class="pull-right">
      <%= link_to '<i class="fa fa-plus "></i> Add'.html_safe, new_customer_path, :class => 'btn btn-success btn-sm' %>
    </div>
  </h1>
</div>

<section class="content">
  <div class="box">
    <div class="box-body table-responsive no-padding">
      <table class="table table-hover">
        <tbody>
          <tr>
            <th>#</th>
            <th><%= model_class.human_attribute_name(:name) %></th>
            <th><%= model_class.human_attribute_name(:address) %></th>
            <th><%= model_class.human_attribute_name(:dni) %></th>
            <th><%= model_class.human_attribute_name(:city) %></th>
            <th><%= model_class.human_attribute_name(:phone) %></th>
            <th><%= model_class.human_attribute_name(:created_at) %></th>
            <th><%=t '.actions', :default => t("helpers.actions") %></th>
          </tr>
          
          <% @customers.each do |customer| %>
            <tr>
              <td><%= link_to customer.id, customer_path(customer) %></td>
              <td><%= customer.name %></td>
              <td><%= customer.address %></td>
              <td><%= customer.dni %></td>
              <td><%= customer.city %></td>
              <td><%= customer.phone %></td>
              <td><%=l customer.created_at %></td>
              <td>
                <%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_customer_path(customer), :class => 'btn btn-xs btn-warning' %>
                <%= link_to '<i class="fa fa-trash-o"></i>'.html_safe,
                            customer_path(customer),
                            :method => :delete,
                            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                            :class => 'btn btn-xs btn-danger' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>

veterinary/app/views/customers/new.html.erb
<%- model_class = Customer -%>
<div class="content-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>

<section class="content">
    <%= render :partial => 'form' %>
</section>

veterinary/app/views/customers/show.html.erb
<%- model_class = Customer -%>
<div class="content-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<section class="content">
    <dl class="dl-horizontal">
      <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
      <dd><%= @customer.name %></dd>
      <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
      <dd><%= @customer.address %></dd>
      <dt><strong><%= model_class.human_attribute_name(:dni) %>:</strong></dt>
      <dd><%= @customer.dni %></dd>
      <dt><strong><%= model_class.human_attribute_name(:city) %>:</strong></dt>
      <dd><%= @customer.city %></dd>
      <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
      <dd><%= @customer.phone %></dd>
    </dl>
    
    <%= link_to t('.back', :default => t("helpers.links.back")),
                  customers_path, :class => 'btn btn-default'  %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_customer_path(@customer), :class => 'btn btn-default' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  customer_path(@customer),
                  :method => 'delete',
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-danger' %>
</section>