veterinary/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:sessions => "sessions"}
  resources :service_orders
  resources :detail_orders
  resources :appointments
  resources :products
  resources :pets
  resources :customers

   root :to => 'appointments#index'

end

veterinary/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Veterinary</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
</head>
<body  class="skin-purple layout-boxed">
  
<!-- Site wrapper -->
    <div class="wrapper">

      <header class="main-header">
        <!-- Logo -->
        <%= link_to '<span class="logo-lg"><b>Ve</b>terinary</span>'.html_safe ,root_path, :class => "logo" %>

        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
          
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <!-- Notifications: style can be found in dropdown.less -->
              <li class="dropdown notifications-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-bell-o"></i>
                  <span class="label label-warning">1</span>
                </a>
                <ul class="dropdown-menu">
                  <li class="header">You have 1 notifications</li>
                  <li>
                    <!-- inner menu: contains the actual data -->
                    <ul class="menu">
                      <li>
                        <a href="#">
                          <i class="fa fa-users text-aqua"></i> 4 new members joined today
                        </a>
                      </li>
                    </ul>
                  </li>
                  <li class="footer"><a href="#">View all</a></li>
                </ul>
              </li>
              <!-- User Account: style can be found in dropdown.less -->
              
              <% if user_signed_in? %>
                <li class="dropdown user user-menu">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <%= image_tag 'user2-160x160.jpg', :class => 'user-image' %>
                    <span class="hidden-xs"><%= current_user.email %></span>
                  </a>
                  <ul class="dropdown-menu">
                    <!-- User image -->
                    <li class="user-header">
                      <%= image_tag 'user2-160x160.jpg', :class => 'img-circle' %>
                      <p>
                       <%= current_user.email %>
                      </p>
                    </li>
                    <!-- Menu Footer-->
                    <li class="user-footer">
                      <div class="pull-left">
                        <%= link_to 'Profile', edit_user_registration_path, :class => 'btn btn-default btn-flat' %>
                      </div>
                      <div class="pull-right">
                        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'btn btn-default btn-flat'  %>
                      </div>
                    </li>
                  </ul>
                </li>
               <% end %>
            </ul>
          </div>
        </nav>
      </header>

      <!-- =============================================== -->

      <!-- Left side column. contains the sidebar -->
      <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
          <!-- sidebar menu: : style can be found in sidebar.less -->
          <ul class="sidebar-menu">
            <li><%= link_to '<i class="fa fa-calendar"></i> Appointments'.html_safe, appointments_path %></li>
            <li><%= link_to '<i class="fa fa-users"></i> Customers'.html_safe, customers_path %></li>
            <li><%= link_to '<i class="fa fa-paw"></i> Pets'.html_safe, pets_path %></li>
            <li><%= link_to '<i class="fa fa-cubes"></i> Products'.html_safe, products_path %></li>
            <li><%= link_to '<i class="fa fa-shopping-cart"></i> Sales'.html_safe, service_orders_path %></li>
          </ul>
        </section>
        <!-- /.sidebar -->
      </aside>

      <!-- =============================================== -->

      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <%= yield %>
      </div><!-- /.content-wrapper -->

      <footer class="main-footer">
        <div class="pull-right hidden-xs">
          <b>Version</b> 1.0
        </div>
        <strong>Copyright &copy; 2015</strong> All rights reserved.
      </footer>

    </div><!-- ./wrapper -->


</body>
</html>

veterinary/app/views/layouts/log_in.html.erb
<html>
  <header>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </header>
  <body class="login-page">
    <div class="login-box">
      <div class="login-logo">
        <b>Ve</b>terinary
      </div>
      <div class="login-box-body">
        <p class="login-box-msg">Sign in to start your session</p>
        <%= yield %>
      </div>
    </div>
  </body>
</html>