veterinary/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:sessions => "sessions"}
  resources :service_orders
  resources :detail_orders
  resources :appointments
  resources :products
  resources :pets
  resources :customers

   root :to => 'appointments#index'

end

veterinary/app/models/service_order.rb
# == Schema Information
#
# Table name: service_orders
#
#  id              :integer          not null, primary key
#  date            :datetime
#  observation     :string(255)
#  price           :integer
#  detail_order_id :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class ServiceOrder < ActiveRecord::Base
  belongs_to :detail_order
end

veterinary/app/controllers/service_orders_controller.rb
class ServiceOrdersController < ApplicationController
  before_action :set_service_order, only: [:show, :edit, :update, :destroy]

  # GET /service_orders
  # GET /service_orders.json
  def index
    @service_orders = ServiceOrder.all
  end

  # GET /service_orders/1
  # GET /service_orders/1.json
  def show
  end

  # GET /service_orders/new
  def new
    @service_order = ServiceOrder.new
  end

  # GET /service_orders/1/edit
  def edit
  end

  # POST /service_orders
  # POST /service_orders.json
  def create
    @service_order = ServiceOrder.new(service_order_params)

    respond_to do |format|
      if @service_order.save
        format.html { redirect_to @service_order, notice: 'Service order was successfully created.' }
        format.json { render :show, status: :created, location: @service_order }
      else
        format.html { render :new }
        format.json { render json: @service_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /service_orders/1
  # PATCH/PUT /service_orders/1.json
  def update
    respond_to do |format|
      if @service_order.update(service_order_params)
        format.html { redirect_to @service_order, notice: 'Service order was successfully updated.' }
        format.json { render :show, status: :ok, location: @service_order }
      else
        format.html { render :edit }
        format.json { render json: @service_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_orders/1
  # DELETE /service_orders/1.json
  def destroy
    @service_order.destroy
    respond_to do |format|
      format.html { redirect_to service_orders_url, notice: 'Service order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_order
      @service_order = ServiceOrder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_order_params
      params.require(:service_order).permit(:date, :observation, :price, :detail_order_id)
    end
end

veterinary/app/helpers/service_orders_helper.rb
module ServiceOrdersHelper
end

veterinary/app/views/service_orders/_form.html.erb
<%= form_for @service_order, :html => { :class => "form-horizontal service_order" } do |f| %>

    <% if @service_order.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@service_order.errors.count, "error") %> prohibited this service_order from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @service_order.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :date, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :date, :class => 'form-control' %>
    </div>
    <%= error_span(@service_order[:date]) %>
  </div>
  <div class="control-group">
    <%= f.label :observation, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :observation, :class => 'form-control' %>
    </div>
    <%= error_span(@service_order[:observation]) %>
  </div>
  <div class="control-group">
    <%= f.label :price, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :price, :class => 'form-control' %>
    </div>
    <%= error_span(@service_order[:price]) %>
  </div>
  <div class="control-group">
    <%= f.label :detail_order_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :detail_order_id, :class => 'form-control' %>
    </div>
    <%= error_span(@service_order[:detail_order_id]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            service_orders_path, :class => 'btn btn-default' %>

<% end %>

veterinary/app/views/service_orders/edit.html.erb
<%- model_class = ServiceOrder -%>
<div class="content-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>

<section class="content">
    <%= render :partial => 'form' %>
</section>

veterinary/app/views/service_orders/index.html.erb
<%- model_class = ServiceOrder -%>
<div class="content-header">
  <h1>
    <%=t '.title', :default => model_class.model_name.human.pluralize.titleize %>
    <div class="pull-right">
      <%= link_to '<i class="fa fa-plus "></i> Add'.html_safe, new_service_order_path, :class => 'btn btn-success btn-sm' %>
    </div>
  </h1>
</div>

<section class="content">
  <div class="box">
    <div class="box-body table-responsive no-padding">
      <table class="table table-hover">
        <tbody>
          <tr>
            <th>#</th>
            <th>Date</th>
            <th><%= model_class.human_attribute_name(:observation) %></th>
            <th><%= model_class.human_attribute_name(:price) %></th>
            <th><%= model_class.human_attribute_name(:detail_order_id) %></th>
            <th>Actions</th>
          </tr>
        
          <% @service_orders.each do |service_order| %>
            <tr>
              <td><%= link_to service_order.id, service_order_path(service_order) %></td>
              <td><%= service_order.date %></td>
              <td><%= service_order.observation %></td>
              <td><%= service_order.price %></td>
              <td><%= service_order.detail_order_id %></td>
              <td>
                <%= link_to '<i class="fa fa-edit"></i>'.html_safe,
                            edit_service_order_path(service_order), :class => 'btn btn-xs btn-warning' %>
                <%= link_to '<i class="fa fa-trash-o"></i>'.html_safe,
                            service_order_path(service_order),
                            :method => :delete,
                            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                            :class => 'btn btn-xs btn-danger' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>

veterinary/app/views/service_orders/new.html.erb
<%- model_class = ServiceOrder -%>
<div class="content-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>

<section class="content">
    <%= render :partial => 'form' %>
</section>

veterinary/app/views/service_orders/show.html.erb
<%- model_class = ServiceOrder -%>
<div class="content-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<section class="content">
    <dl class="dl-horizontal">
      <dt><strong><%= model_class.human_attribute_name(:date) %>:</strong></dt>
      <dd><%= @service_order.date %></dd>
      <dt><strong><%= model_class.human_attribute_name(:observation) %>:</strong></dt>
      <dd><%= @service_order.observation %></dd>
      <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
      <dd><%= @service_order.price %></dd>
      <dt><strong><%= model_class.human_attribute_name(:detail_order_id) %>:</strong></dt>
      <dd><%= @service_order.detail_order_id %></dd>
    </dl>
    
    <%= link_to t('.back', :default => t("helpers.links.back")),
                  service_orders_path, :class => 'btn btn-default'  %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_service_order_path(@service_order), :class => 'btn btn-default' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  service_order_path(@service_order),
                  :method => 'delete',
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-danger' %>
</section>