veterinary/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:sessions => "sessions"}
  resources :service_orders
  resources :detail_orders
  resources :appointments
  resources :products
  resources :pets
  resources :customers

   root :to => 'appointments#index'

end

veterinary/app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id           :integer          not null, primary key
#  name         :string(255)
#  description  :string(255)
#  product_type :string(255)
#  cost         :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Product < ActiveRecord::Base
end

veterinary/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :product_type, :cost)
    end
end

veterinary/app/helpers/products_helper.rb
module ProductsHelper
end

veterinary/app/views/products/_form.html.erb
<%= simple_form_for @product do |f| %>

    <% if @product.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@product[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%= error_span(@product[:description]) %>
  </div>
  <div class="control-group">
    <%= f.label :product_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :product_type, :class => 'form-control' %>
    </div>
    <%= error_span(@product[:product_type]) %>
  </div>
  <div class="control-group">
    <%= f.label :cost, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :cost, :class => 'form-control' %>
    </div>
    <%= error_span(@product[:cost]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            products_path, :class => 'btn btn-default' %>

<% end %>

veterinary/app/views/products/edit.html.erb
<%- model_class = Product -%>
<div class="content-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>

<section class="content">
    <%= render :partial => 'form' %>
</section>

veterinary/app/views/products/index.html.erb
<%- model_class = Product -%>
<div class="content-header">
  <h1>
    <%=t '.title', :default => model_class.model_name.human.pluralize.titleize %>
    <div class="pull-right">
      <%= link_to '<i class="fa fa-plus "></i> Add'.html_safe, new_product_path, :class => 'btn btn-success btn-sm' %>
    </div>
  </h1>
</div>

<section class="content">
  <div class="box">
    <div class="box-body table-responsive no-padding">
      <table class="table table-hover">
        <tbody>
          <tr>
            <th>#</th>
            <th><%= model_class.human_attribute_name(:name) %></th>
            <th><%= model_class.human_attribute_name(:description) %></th>
            <th><%= model_class.human_attribute_name(:product_type) %></th>
            <th><%= model_class.human_attribute_name(:cost) %></th>
            <th><%= model_class.human_attribute_name(:created_at) %></th>
            <th><%=t '.actions', :default => t("helpers.actions") %></th>
          </tr>
       
          <% @products.each do |product| %>
            <tr>
              <td><%= link_to product.id, product_path(product) %></td>
              <td><%= product.name %></td>
              <td><%= product.description %></td>
              <td><%= product.product_type %></td>
              <td><%= product.cost %></td>
              <td><%=l product.created_at %></td>
              <td>
                <%= link_to '<i class="fa fa-edit"></i>'.html_safe,
                            edit_product_path(product), :class => 'btn btn-xs btn-warning' %>
                <%= link_to '<i class="fa fa-trash-o"></i>'.html_safe,
                            product_path(product),
                            :method => :delete,
                            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                            :class => 'btn btn-xs btn-danger' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>

veterinary/app/views/products/new.html.erb
<%- model_class = Product -%>
<div class="content-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>

<section class="content">
    <%= render :partial => 'form' %>
</section>

veterinary/app/views/products/show.html.erb
<%- model_class = Product -%>
<div class="content-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<section class="content">
    <dl class="dl-horizontal">
      <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
      <dd><%= @product.name %></dd>
      <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
      <dd><%= @product.description %></dd>
      <dt><strong><%= model_class.human_attribute_name(:product_type) %>:</strong></dt>
      <dd><%= @product.product_type %></dd>
      <dt><strong><%= model_class.human_attribute_name(:cost) %>:</strong></dt>
      <dd>S/. <%= @product.cost %> </dd>
    </dl>
    
    <%= link_to t('.back', :default => t("helpers.links.back")),
                  products_path, :class => 'btn btn-default'  %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_product_path(@product), :class => 'btn btn-default' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  product_path(@product),
                  :method => 'delete',
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-danger' %>
</section>